name: PythonRun
on:
  workflow_dispatch

jobs:
  Build-and-deploy-Wheel:
    name: Build Wheel
    runs-on: ubuntu-latest

    steps:
    - name: Run Python
      run: |
        python print('hello')

